name: Deploy Multilingual Site

on:
  release:
    types: [published]

permissions:
  contents: write  # Даем права на запись содержимого

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Create versioned directory
      run: |
        VERSION=v${{ github.event.release.tag }}
        mkdir -p $VERSION
        cp ./index.html ./$VERSION/index.html
        cp ./ru.html ./$VERSION/ru.html
        cp ./en.html ./$VERSION/en.html

    - name: Check contents of the versioned directory
      run: |
        echo "Contents of the directory:"
        ls -la v${{ github.event.release.tag }}

    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.KATE_TOKEN }}
        publish_dir: ./
        keep_files: true  # Не удаляем старые файлы


