name: Deploy Multilingual Site

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Create versioned directory
      run: mkdir -p v${{ github.event.release.tag }}

    - name: Copy HTML files to versioned directory
      run: |
        cp ./index.html ./v${{ github.event.release.tag }}/index.html
        cp ./ru.html ./v${{ github.event.release.tag }}/ru.html
        cp ./en.html ./v${{ github.event.release.tag }}/en.html

    - name: Check contents of the versioned directory
      run: |
        echo "Contents of the v${{ github.event.release.tag }} directory:"
        ls -la v${{ github.event.release.tag }}

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and push to gh-pages
      run: |
        git add .
        git commit -m "Deploy version ${{ github.event.release.tag }}"
        git push origin HEAD:gh-pages --force
