name: Deploy Multilingual Site

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Create versioned directory
      run: |
        VERSION_DIR="v${{ github.event.release.tag }}"
        mkdir -p $VERSION_DIR

    - name: Copy HTML files to versioned directory
      run: |
        VERSION_DIR="v${{ github.event.release.tag }}"
        cp ./index.html ./$VERSION_DIR/index.html
        cp ./ru.html ./$VERSION_DIR/ru.html
        cp ./en.html ./$VERSION_DIR/en.html

    - name: Check contents of the versioned directory
      run: |
        VERSION_DIR="v${{ github.event.release.tag }}"
        echo "Contents of the $VERSION_DIR directory:"
        ls -la $VERSION_DIR

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.KATE_TOKEN }}
        publish_dir: ./
        keep_files: true

